### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tancheng** [tancheng/VectorCGRA#4]
- [ ] Tutorial and scripts for control signals.
- [ ] Need to avoid combinational loop caused by the for statement in the always block.
- [ ] Current support of predication only allows one predication-based operation mapped onto one CGRA tile.

**Comment by emrahuzucar355** [comment]
> - [ ] Tutorial and scripts for control signals.
> 
>   - [ ] Control signal documentation and easy way to program: https://github.com/tancheng/VectorCGRA/issues/28
> 
> - [ ] ~~Need to avoid combinational loop caused by the for statement in the always block.~~ Duplicated: https://github.com/tancheng/VectorCGRA/issues/39 & https://github.com/tancheng/VectorCGRA/issues/51
> 
> - [ ] ~~Current support of predication only allows one predication-based operation mapped onto one CGRA tile.~~ Duplicated: https://github.com/tancheng/VectorCGRA/issues/27
